[package]
name = "vk-wrapper"
version = "0.1.0"
authors = ["MotanGish <motangish@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
bitflags = "1.2.1"
log = "0.4.11"
ahash = "0.6.3"
ash = "0.31.0"
ash-window = "0.5.0"
raw-window-handle = "0.3.3"
vk-mem = "0.2.2"
spirv_cross = { version = "0.22.1", features = ["glsl"] }