[package]
name = "marching-cubes"
version = "0.1.0"
authors = ["a7292969 <a7292969@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
smallvec = "1.6.1"
nalgebra = "0.24.1"
lazy_static = "1.4.0"