[package]
name = "res-encoder"
version = "0.1.0"
authors = ["a7292969 <motangish@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.4.3"
bincode = "1.3.3"