[package]
name = "base"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
simple_logger = "4.0"
nalgebra = "0.32"
nalgebra-glm = "0.18"
image = { version = "0.24", default-features = false, features = ["png"] }
rayon = "1.6"
crossbeam-channel = "0.5"
noise = { version = "0.8", default-features = false }
rand = "0.8"
rand_distr = "0.4"
approx = "0.5"
entity_data = "1.9"
#entity_data = { path = "../../entity_data" }
smallvec = "1.6"
bit-vec = "0.6"
fixedbitset = "0.4"
replace_with = "0.1"
lazy_static = "1.4"
parking_lot = { version = "0.12", features = ["arc_lock", "hardware-lock-elision", "deadlock_detection"] }
once_cell = "1.17"
rstar = "0.9"
bumpalo = "3.11"
index-pool = "1.0"
rand_xoshiro = "0.6"
byteorder = "1.4"
ahash = "0.8"
moka = "0.9"
indexmap = "1.9"
async-executor = "1.5"
async-channel = "1.8"
futures-lite = "1.12"

[target.'cfg(target_os = "macos")'.dependencies]
macos = { path = "macos" }
